### ISSUE TITLE
download certs

### ISSUE THREAD

**Issue by ohayon** [pj4533/lightman#6]
sometimes lightman times out before cert is ready. (seems to only be distribution certs)

**Comment by pj4533** [comment]
So when the cert is downloaded, since it is still 'pending' it appears to work, but really just downloaded HTML.

**Comment by ohayon** [comment]
think its cool to close this? hahaha

**Comment by pj4533** [comment]
Wow...cleaning up your open source footprint or something?   I should get rid of this whole repo....
